ci: branch protection rule

diff --git a/.github/workflows/normal.yaml b/.github/workflows/normal.yaml
--- a/.github/workflows/normal.yaml
+++ b/.github/workflows/normal.yaml
@@ -10,6 +10,21 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  # Aggregate check for protection rule.
+  checks-all:
+    if: always()
+    needs:
+      - build
+      - eval
+    runs-on: ubuntu-latest
+    steps:
+      - name: Verify all matrix jobs passed
+        run: |
+          if [[ "${{ needs.checks.result }}" != "success" ]]; then
+            echo "One or more checks failed: ${{ needs.checks.result }}"
+            exit 1
+          fi
+
   eval:
     name: eval ${{ matrix.nixos }} (installer=${{ matrix.installer }}, cross=${{ matrix.cross }})
     runs-on: ubuntu-latest
